baseURL = "https://askiesec.blog/"
languageCode = "en-us"
title = "Askiesec"
theme = "askiesec"

[params]
author = "askiesec"


[[menu.main]]
  name = "writeups"
  url = "/writeups/"
  weight = 1

[[menu.main]]
  name = "posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "tools"
  url = "/tools/"
  weight = 3

[markup]
  [markup.highlight]
    style = "gruvbox"
    noClasses = true
    lineNos = false
    codeFences = true
    guessSyntax = true
    