baseURL = "https://askiesec.blog/"
languageCode = "en-us"
title = "Askiesec"
theme = "cyber-minimal"

[params]
  author = "askiesec"
  mainSections = ["posts", "writeups", "tools"] 

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "writeups"
  url = "/writeups/"
  weight = 2

[[menu.main]]
  name = "posts"
  url = "/posts/"
  weight = 3

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "gruvbox"
    noClasses = true
    lineNos = false
    codeFences = true
    guessSyntax = true
